services:
  - type: web
    name: caliskanel-bcs-teklif
    env: python
    buildCommand: pip install -r backend/requirements.txt && cd frontend && npm install && npm run build
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    buildFilter:
      paths:
        - backend/**
        - frontend/**
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

